services:
  webapptrip2guide:
    image: joelrojasllauradoupc/webapptrip2guide:1.1.0-mapa_ruta11
    ports:
      - "5173:5173"
    depends_on:
      - backendtrip2guide
    env_file:
      - .env.${DOCKER_PROFILE}

  backofficetrip2guide:
    image: joelrojasllauradoupc/backofficetrip2guide:1.1.0-merge_historial
    ports:
      - "4200:4200"
    depends_on:
      - backendtrip2guide
    env_file:
      - .env.${DOCKER_PROFILE}

  backendtrip2guide:
    image: joelrojasllauradoupc/backendtrip2guide:1.1.0-merge_historial
    ports:
      - "1337:1337"
    depends_on:
      - mongodb
    env_file:
      - .env.${DOCKER_PROFILE}

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

x-environment-variables:
  profiles:
    development:
      DOCKER_PROFILE: development
    production:
      DOCKER_PROFILE: production
